#!/bin/bash
echo "Client or Server?"
echo "1) Client"
echo "2) Server"
read input
if [[ $input == 1 ]]; then
    echo "Starting Just Another Python IRC Client..."
    cd ~/.python3/JAPIRC/
    source ~/.python3/JAPIRC/bin/activate
    python3 ~/.python3/JAPIRC/client.py
elif [[ $input == 2 ]]; then
    echo "Starting Just Another Python IRC Client..."
    cd ~/.python3/JAPIRC/
    source ~/.python3/JAPIRC/bin/activate
    python3 ~/.python3/JAPIRC/server.py
else
    echo "Invalid input"
fi
