#!/bin/bash
echo "Client or Server?"
echo "1) Client (TUI)"
echo "2) Client (GUI)"
echo "3) Server"
read input
if [[ $input == 1 ]]; then
    echo "Starting Just Another Python IRC TUI Client..."
    cd ~/.python3/JAPIRC/
    source ~/.python3/JAPIRC/bin/activate
    python3 ~/.python3/JAPIRC/JAPIRC_TUI.client.py
elif [[ $input == 2 ]]; then
    echo "Starting Just Another Python IRC GUI Client..."
    cd ~/.python3/JAPIRC/
    source ~/.python3/JAPIRC/bin/activate
    python3 ~/.python3/JAPIRC/JAPIRC_GUI.client.py
elif [[ $input == 3 ]]; then
    echo "Starting Just Another Python IRC CLI Server..."
    cd ~/.python3/JAPIRC/
    source ~/.python3/JAPIRC/bin/activate
    python3 ~/.python3/JAPIRC/JAPIRC_CLI.server.py
else
    echo "Invalid input"
fi
