#!/bin/bash
echo "Client or Server?"
echo "1) Client"
echo "2) Server"
read input
if [[ $input == 1 ]]; then
    echo "Starting PyChatCLI Client"
    cd ~/.python3/PyChatCLI/
    source ~/.python3/PyChatCLI/bin/activate
    python3 ~/.python3/PyChatCLI/client.py
elif [[ $input == 2 ]]; then
    echo "Starting PyChatCLI Server"
    cd ~/.python3/PyChatCLI/
    source ~/.python3/PyChatCLI/bin/activate
    python3 ~/.python3/PyChatCLI/server.py
else
    echo "Invalid input"
fi
